import { useStudyLanguage } from '../../study/i18n/StudyLanguageContext';
import { ArrowLeft } from 'lucide-react';
import { NavLink } from 'react-router-dom';

const privacyContentKR = `
1) 개인정보처리방침 안내
본 개인정보처리방침은 dominik.tyrnel.com 및 관련 서비스(학습 대시보드(/study), 스터디룸, 계정, FAQ/문의, 향후 알림 기능)에 적용됩니다.
개인정보처리자(관리자): Dominik Tyrnel (개인)
국가: 체코(유럽연합)
문의 이메일: dominiktyrnel@gmail.com

2) 수집하는 개인정보
2.1 이용자가 제공하는 정보
계정/프로필: 이메일, @handle(아이디), (선택) 표시 이름, (선택) 자기소개, 선호 언어, 프로필 이미지(아바타), (선택) 소셜 링크(YouTube/Instagram/Discord/X).
FAQ/문의: 이용자가 작성한 내용, 선택한 카테고리, FAQ 공개 동의 여부.

2.2 서비스 이용 과정에서 생성되는 정보
학습 기록(기능 제공 시): Focus/Break 등 세션 이벤트, 시간 정보, 기록/연속학습/타임라인 표시를 위한 기본 수치.
상태(향후 기능): "Studying / On break / Offline" 등은 이용 활동 및/또는 연동(봇 이벤트 등)에 따라 반영될 수 있으며, 공개 설정이 제공될 수 있습니다.

2.3 기술 정보(보안/악용 방지)
서비스 보안 및 스팸/악용 방지를 위해 최소한의 기술 로그(IP, 기기/브라우저 정보, 접속 시각 등)를 처리할 수 있으며, 필요 최소한으로 제한합니다.

3) 처리 목적
(1) 서비스 제공 및 운영(계정, 학습 페이지, FAQ/문의)
(2) 보안 및 악용 방지(스팸 차단, 보안 모니터링)
(3) 문의 응대 및 공지
(4) 알림 발송(이용자 동의(Opt-in) 시)
(5) 관련 법령 준수

4) 쿠키 및 유사 기술
로그인/보안 등 필수 기능을 위해 필수 쿠키를 사용할 수 있습니다.
향후 분석/마케팅 쿠키를 도입하는 경우, 필요한 동의를 받고 쿠키 설정을 제공할 수 있습니다.
YouTube 등 외부 임베드 콘텐츠는 제3자 쿠키 및 정책이 적용될 수 있습니다.

5) 제3자 제공 및 외부 링크
당사는 개인정보를 판매하지 않습니다.
서비스 운영을 위해 호스팅/DB/알림 발송 등 제공업체에 필요한 범위 내에서 개인정보 처리를 위탁할 수 있습니다.
KakaoTalk 1:1 링크 클릭 시 웹사이트 밖의 카카오 서비스로 이동하며, 카카오의 정책이 적용됩니다(YouTube 등 외부 링크도 동일).

6) 보유 및 이용기간
계정/프로필: 계정 유지 기간 동안.
FAQ/문의: 문의 처리 및 FAQ 관리 목적 달성 시까지(공개 동의한 경우 FAQ로 유지될 수 있음).
학습 기록: 기능 제공 및 기록 표시 목적에 필요한 기간 동안(설정에 따라 집계/삭제될 수 있음).
보안 로그: 보안/악용 방지를 위한 제한된 기간 동안.

7) 이용자의 권리
(EU/GDPR) 열람/정정/삭제/처리 제한/이동/이의 제기 및 동의 철회 요청이 가능합니다. 문의: dominiktyrnel@gmail.com
체코 감독기관(ÚOOÚ)에 민원 제기가 가능합니다.
(한국/PIPA) 한국에 거주하는 이용자는 PIPA에 따라 열람/정정/삭제/처리정지 요구 등의 권리를 행사할 수 있습니다.

8) 아동
본 서비스는 만 16세 미만 아동을 대상으로 하지 않습니다. 아동 정보가 수집된 것으로 판단되면 이메일로 연락해 주세요.

9) 변경
본 방침이 변경될 경우 "Last updated" 날짜를 갱신하며, 중요한 변경은 웹사이트에 공지할 수 있습니다.
`;

const privacyContentEN = `
1) Who we are (Controller)
This Privacy Policy applies to dominik.tyrnel.com and its related services (the "Service"), including: Study dashboard (/study), Study Room access, user accounts, FAQ/contact form, and future notifications.
Controller: Dominik Tyrnel (individual)
Country: Czech Republic (EU)
Contact email: dominiktyrnel@gmail.com

2) What personal data we collect
2.1 Data you provide
Account and profile: email, @handle (username), optional display name, optional bio, preferred language, profile image (avatar), optional links you add (YouTube/Instagram/Discord/X).
FAQ/Contact: the text you submit, the selected category, and whether you allow publishing your question on the public FAQ.

2.2 Data generated by using the Service
Study/records (when enabled): session events (e.g., focus/break), timestamps, and basic counters needed to display your records, streaks, and timeline.
Status (future feature): "Studying / On break / Offline" may be derived from your activity and/or integrations (e.g., bot events). Visibility controls may be offered in settings.

2.3 Technical data (security/abuse prevention)
We may process minimal technical logs necessary to secure the Service and prevent abuse (for example IP address, device/browser info, timestamps). We try to minimize this data.

3) Why we process data (purposes)
We process your data to:
(a) provide and operate the Service (accounts, Study pages, FAQ submissions);
(b) keep the Service safe (security monitoring, spam prevention, abuse handling);
(c) communicate with you (answers to your questions, service notices);
(d) send notifications if you opt in (web/app push);
(e) comply with legal obligations where required.

4) Cookies and similar technologies
We may use essential cookies for login/session security and core site functionality.
If we add analytics or marketing cookies in the future, we will request consent where required and provide cookie controls.
Embedded third-party content (for example YouTube) may set its own cookies and process data under its own policies.

5) Sharing and third parties
We do not sell your personal data.
We may share data with service providers that host or support the Service (hosting, databases, email/push providers) only as needed to run the Service and maintain security.
Third-party links: If you click the KakaoTalk 1:1 chat link, you leave our Site and your interaction is governed by Kakao's policies.

6) Retention (how long we keep data)
Account/profile data: stored while your account is active.
FAQ/contact submissions: stored to respond and maintain FAQ history (if you allow publishing).
Study/records logs: stored while the feature is enabled and as needed to display your records.
Security logs: stored for a limited period necessary to prevent abuse and secure the Service.

7) Your rights
EEA/EU (GDPR): You can request access, correction, deletion, restriction, portability, object to processing, and withdraw consent.
South Korea (PIPA): If you are in South Korea, you may have rights to request access, correction, deletion, and suspension of processing under PIPA.
Contact: dominiktyrnel@gmail.com

8) Children
The Service is not intended for children under 16. If you believe a child has provided personal data, contact us and we will remove it.

9) Changes to this Policy
We may update this Privacy Policy. We will update the "Last updated" date and, if changes are significant, we may post a notice on the Site.
`;

export function StudyPrivacyPage() {
    const { studyLang } = useStudyLanguage();

    const content = studyLang === 'kr' ? privacyContentKR : privacyContentEN;
    const title = studyLang === 'kr' ? '개인정보 처리방침' : 'Privacy Policy';

    return (
        <div className="min-h-screen bg-[var(--study-bg)] pt-24 pb-20 px-4 md:px-8 max-w-4xl mx-auto">
            {/* Back Button */}
            <NavLink
                to="/study/now"
                className="inline-flex items-center gap-2 text-[var(--study-text-muted)] hover:text-[var(--study-text)] mb-8 transition-colors"
            >
                <ArrowLeft size={18} />
                {studyLang === 'kr' ? '돌아가기' : 'Go Back'}
            </NavLink>

            {/* Header */}
            <h1 className="text-3xl font-bold text-[var(--study-text)] mb-2 font-heading">{title}</h1>
            <p className="text-[var(--study-text-muted)] text-sm mb-8">
                Last updated: 2025-12-25
            </p>

            {/* Content */}
            <div className="bg-[var(--study-surface)] border border-[var(--study-border)] rounded-xl p-6 md:p-8">
                <div className="prose prose-study max-w-none">
                    {content.split('\n\n').map((paragraph, index) => (
                        <p key={index} className="text-[var(--study-text)] mb-4 whitespace-pre-line leading-relaxed">
                            {paragraph}
                        </p>
                    ))}
                </div>
            </div>
        </div>
    );
}
